[package]
name = "Eratosthenes"
version = "0.1.0"
authors = [ "Askhat Bikmetov <lolborgini@gmail.com>" ]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.50"
js-sys = "0.3.35"

[lib]
crate-type = [ "cdylib" ]
